export { default as AboutSection } from './AboutSection';
export { default as Background } from './Background';
export { default as ContactSection } from './ContactSection';
export { default as ExperienceSection } from './ExperienceSection';
export { default as Footer } from './Footer';
export { default as HeroSection } from './HeroSection';
export { default as Navigation } from './Navigation';
export { default as TechStackSection } from './TechStackSection';
export { default as WorkSection } from './WorkSection';
