// Builds cv/cv.tex from the site content in src/data/profile.ts.
// Usage: npm run cv  (writes cv/cv.tex, compiles it and copies the PDF to public/CV.pdf)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { certificates, education, experience, profile, skills } from "../src/data/profile.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Escape LaTeX special characters in plain text.
const tex = (s: string) =>
  s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/ — /g, " – ");

const headerLink = (href: string, icon: string, label: string, size = "") =>
  `\\mbox{\\hrefWithoutArrow{${href}}{\\color{NavyBlue}${size}\\atsHide{${icon}}\\hspace*{0.13cm}{\\color{black}${label}}}}%`;

const separator = ["\\kern 0.1 cm%", "\\AND%", "\\kern 0.1 cm%"].join("\n        ");

const header = `    \\begin{header}
        \\textbf{\\color{NavyBlue}\\fontsize{28 pt}{30 pt}\\selectfont ${tex(profile.name)}}

        {\\large ${tex(profile.role)}}

        \\normalsize
        \\mbox{\\color{NavyBlue}\\atsHide{\\faIcon{location-arrow}}\\hspace*{0.13cm}{\\color{black}${tex(profile.location)}}}%

        ${[
          headerLink(`mailto:${profile.email}`, "\\faEnvelope", tex(profile.email)),
          headerLink(profile.phone.href, "\\faPhone*", tex(profile.phone.display), "\\footnotesize"),
          headerLink(profile.socials.linkedin, "\\faLinkedin", "LinkedIn"),
          headerLink(profile.socials.upwork, "\\faIcon{laptop-code}", "Upwork"),
          headerLink(profile.socials.github, "\\faGithub", "GitHub"),
          headerLink(profile.siteUrl, "\\faExternalLinkSquare*", "Portfolio"),
        ].join(`\n        ${separator}\n        `)}
    \\end{header}`;

const highlights = (items: string[]) =>
  ["            \\begin{highlights}", ...items.map((i) => `                \\item ${tex(i)}`), "            \\end{highlights}"].join("\n");

const roles = experience
  .map((role) => {
    const company = role.companyUrl ? `\\hrefWithoutArrow{${role.companyUrl}}{${tex(role.company)}}` : tex(role.company);
    const items = role.groups ? role.groups.flatMap((g) => g.items) : (role.highlights ?? []);
    return `        \\begin{onecolentry}
            \\textbf{${tex(role.title)}} \\hfill \\textit{${tex(role.period)}} \\\\
            ${company} \\textendash{} ${tex(role.context.replace(/\.$/, "")).replace(/^./, (c) => c.toLowerCase())}
${highlights(items)}
        \\end{onecolentry}`;
  })
  .join("\n        \\vspace{0.1 cm}\n");

const skillRows = skills
  .map((row) => `        \\begin{onecolentry}
            \\textbf{${tex(row.group.replace(/^./, (c) => c.toUpperCase()))}:} ${tex(row.items.join(", "))}
        \\end{onecolentry}`)
  .join("\n");

const educationRows = education
  .map((item) => `        \\begin{onecolentry}
            \\textbf{${tex(item.degree)}} \\hfill \\textit{${tex(item.period)}} \\\\
            \\hrefWithoutArrow{${item.url}}{${tex(item.school)}}
        \\end{onecolentry}`)
  .join("\n        \\vspace{0.1 cm}\n");

// Group certificates by issuer so they take a few lines instead of a page.
const byIssuer = new Map<string, string[]>();
for (const cert of certificates) {
  const key = `${cert.issuer} (${cert.platform})`;
  byIssuer.set(key, [...(byIssuer.get(key) ?? []), `${cert.title} (${cert.issued})`]);
}
const certificateRows = [...byIssuer]
  .map(([issuer, titles]) => `        \\begin{onecolentry}
            \\textbf{${tex(issuer)}:} ${tex(titles.join("; "))}
        \\end{onecolentry}`)
  .join("\n");

const document = `% Generated by scripts/generate-cv.mts from src/data/profile.ts. Do not edit by hand.
${readFileSync(join(root, "cv/preamble.tex"), "utf8").replace(/^% Preamble.*\n/, "").replace("pdftitle={Muhammad Ramazan's CV}", `pdftitle={${profile.name}'s CV}`)}
\\begin{document}
    \\newcommand{\\AND}{\\unskip
        \\cleaders\\copy\\ANDbox\\hskip\\wd\\ANDbox
        \\ignorespaces
    }
    \\newsavebox\\ANDbox
    \\sbox\\ANDbox{}

    \\placelastupdatedtext
${header}

    \\vspace{0.1 cm - 0.1 cm}
    \\section{Summary}
    \\begin{onecolentry}
      ${tex(profile.cvSummary)}
    \\end{onecolentry}

    \\section{Experience}
${roles}

    \\section{Skills}
${skillRows}

    \\section{Education}
${educationRows}

    \\section{Certifications}
${certificateRows}

\\end{document}
`;

writeFileSync(join(root, "cv/cv.tex"), document);
console.log("Wrote cv/cv.tex");
